volumes:
  pg_data:

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  alembic-migrations:
    build: .
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://user:password@postgres:5432/auth
    restart: "no"
    command: >
      alembic upgrade head
