"""Изменение поля password

Revision ID: da5404445050
Revises: 557756755976
Create Date: 2024-12-12 17:45:50.528922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da5404445050"
down_revision: Union[str, None] = "557756755976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(op.f("uq_users_id"), "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_id"), "users", type_="unique")
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
