"""каскадное удаление истории юзера

Revision ID: 7abe9c38a6cd
Revises: 6cce8b8c000a
Create Date: 2024-12-23 00:33:06.304159

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7abe9c38a6cd'
down_revision: Union[str, None] = '6cce8b8c000a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_login_history_user_id_users', 'login_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_login_history_user_id_users'), 'login_history', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.create_unique_constraint(op.f('uq_roles_id'), 'roles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_roles_id'), 'roles', type_='unique')
    op.drop_constraint(op.f('fk_login_history_user_id_users'), 'login_history', type_='foreignkey')
    op.create_foreign_key('fk_login_history_user_id_users', 'login_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
