"""Add LoginHistory model

Revision ID: f966d4bebbcc
Revises: f3a928b44635
Create Date: 2024-12-20 00:22:55.942169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f966d4bebbcc'
down_revision: Union[str, None] = 'f3a928b44635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'login_history',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_login_history_user_id_users'),
        sa.PrimaryKeyConstraint('id', name='pk_login_history')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_history')
    # ### end Alembic commands ###
