"""user.birth_date added

Revision ID: b26baf4c5fc3
Revises: 8483a86bc196
Create Date: 2025-03-20 13:52:11.664983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b26baf4c5fc3"
down_revision: Union[str, None] = "8483a86bc196"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_oauth_accounts_id"), "oauth_accounts", ["id"]
    )
    op.create_unique_constraint(
        op.f("uq_oauth_providers_id"), "oauth_providers", ["id"]
    )
    op.add_column("users", sa.Column("birth_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "birth_date")
    op.drop_constraint(
        op.f("uq_oauth_providers_id"), "oauth_providers", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_oauth_accounts_id"), "oauth_accounts", type_="unique"
    )
    # ### end Alembic commands ###
