"""return User.oauth_accounts

Revision ID: 9997eb287b5c
Revises: 895e36f6e10c
Create Date: 2025-04-15 15:14:15.528380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9997eb287b5c"
down_revision: Union[str, None] = "895e36f6e10c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_oauth_accounts_id"), "oauth_accounts", ["id"]
    )
    op.create_unique_constraint(
        op.f("uq_oauth_providers_id"), "oauth_providers", ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_oauth_providers_id"), "oauth_providers", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_oauth_accounts_id"), "oauth_accounts", type_="unique"
    )
    # ### end Alembic commands ###
